apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: naveenkendyala789-poi-map-app-dev
  annotations:
    argocd/app-name: naveenkendyala789-poi-map-app-dev
    backstage.io/kubernetes-id: naveenkendyala789-poi-map-app
    backstage.io/kubernetes-namespace: naveenkendyala789
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-ms/naveenkendyala789-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.igb2792k.eastus2.aroapp.io/dev-pipelines/ns/naveenkendyala789/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.igb2792k.eastus2.aroapp.io/k8s/ns/naveenkendyala789/deployments/naveenkendyala789-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.igb2792k.eastus2.aroapp.io/#https://github.com/rhdh-ms/naveenkendyala789-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://naveenkendyala789-poi-map-app-naveenkendyala789.apps.igb2792k.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/naveenkendyala789"
  system: workshop-system-naveenkendyala789
  consumesApis:
    - gateway-api-naveenkendyala789
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-naveenkendyala789
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/naveenkendyala789"
